name: Terraform Plan

on:
  push:
    branches:
      - main

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Terraform Plan

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Terraform
        working-directory: ./aws/terraform/control-tower
        run: terraform init -reconfigure

      - name: Terraform Plan
        working-directory: ./aws/terraform/control-tower
        run: terraform plan -var-file="../terraform.tfvars" -out=tfplan
