name: Deploy Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials with OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    # Deploy Control Tower Resources
    - name: Set up Terraform for Control Tower
      working-directory: ./aws/terraform/control-tower
      run: |
        terraform init
        terraform apply -auto-approve

    # Deploy Shared Account Resources
    - name: Set up Terraform for Shared Account
      working-directory: ./aws/terraform/shared
      run: |
        terraform init
        terraform apply -auto-approve
