name: "Terraform Import"

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows the workflow to be triggered manually

jobs:
  plan-iam:
    runs-on: ubuntu-latest
    name: Terraform Import Bootstrap

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_CONTROL_TOWER }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Terraform Init create Control Tower accounts
        working-directory: ./aws/terraform/control-tower/account
        run: terraform init -reconfigure

      - name: Terraform Import Control Tower accounts
        working-directory: ./aws/terraform/account
        run: terraform import

